---
- hosts: karst
  remote_user: scmcclar
  vars_files:
  - vars/daart
  tasks:
  - name: Run DAART uninstall scripts in {{ daart_path }}
    command: sh "{{ daart_path }}"/scripts/uninstall.sh
  - name: Remove DAART source code {{ daart_path }}
    file: state=absent path="{{ daart_path }}"
